name: build

on: ["push", "pull_request"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./example
          platforms: linux/amd64,linux/arm64
          push: false
          tags: amieldelatorre/test-repo:test