name: New Tag Created

on:
  push:
    tags:
      - "**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-webapi

jobs:
  # build:
  #   uses: ./.github/workflows/build.yml

  push:
    # needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata amd64
        id: metadata-amd64
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest
          flavor: |
            latest=false
            suffix=-amd64

      - name: Build and push
        id: push-amd64
        uses: docker/build-push-action@v5
        with:
          context: ./example
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata-amd64.outputs.tags }}

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push-amd64.outputs.digest }}
          push-to-registry: true

      - name: Docker metadata arm64
        id: metadata-arm64
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest
          flavor: |
            latest=false
            suffix=-arm64

      - name: Build and push
        id: push-arm64
        uses: docker/build-push-action@v5
        with:
          context: ./example
          platforms: linux/arm64
          push: true
          tags: ${{ steps.metadata-arm64.outputs.tags }}

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push-arm64.outputs.digest }}
          push-to-registry: true

      - name: Docker metadata unified
        id: metadata-unified
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest
          flavor: |
            latest=false

      - name: Create and push multi-platform manifest
        run: |
          tags_list_arm64=$(${{ steps.metadata-arm64.outputs.tags }})
          tags_list_amd64=$(${{ steps.metadata-amd64.outputs.tags }})
          tags_list_unified=$(${{ steps.metadata-unified.outputs.tags }})

          docker manifest create "${tags_list_unified[@]}" "${tags_list_arm64[@]}" "${tags_list_amd64[@]}"
          docker manifest annotate "${tags_list_unified[@]}" "${tags_list_arm64[@]}" --arch arm64
          docker manifest annotate "${tags_list_unified[@]}" "${tags_list_amd64[@]}" --arch amd64

  # release:
  # needs: [push]
  # runs-on: ubuntu-latest
  # permissions:
  #   contents: write
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Update release
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       TAG: ${{ github.ref_name }}
  #     run: gh release create "$TAG" --title="$TAG" --notes-file ./CHANGELOG.md
  # run: |
  #   pwd
  #   gh release create "$TAG" \
  #     --title="$TAG"
  #     --repo="$GITHUB_REPOSITORY" \
  #     --notes-file ./CHANGELOG.md
