name: New Tag Created

on: 
  push:
    tags:
      - '**'

jobs:
  # build:
  #   uses: ./.github/workflows/build.yml

  # push:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Setup Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
        
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./example
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: amieldelatorre/test-repo:${{  github.ref_name }},amieldelatorre/test-repo:latest
    
  release:
    # needs: [push]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: gh release create "$TAG" --title="$TAG"
          # gh release create "$TAG" --title="$TAG" --notes-file ./CHANGELOG.md
        # run: |
        #   pwd
        #   gh release create "$TAG" \
        #     --title="$TAG"
        #     --repo="$GITHUB_REPOSITORY" \
        #     --notes-file ./CHANGELOG.md