name: New Tag

on: 
  push:
    tags:
      - '**'

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: GIVE NAME
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"